# Copyright 2011 Aalok Shah. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=github.com/pomack/jsonhelper.go/jsonhelper
GOFILES=\
    encode.go\
    helper.go\
    jsonarray.go\
    jsonobject.go\
    tags.go


include $(GOROOT)/src/Make.pkg
